// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
#[warn(single_use_lifetimes)]
mod imp {
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;

    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("memwatch_bpf")
            .map("msg_ringbuf", false)
            .map("memwatch.bss", true)
            .map("memwatch.rodata", false)
            .prog("perf_event_handler");

        builder.build()
    }

    #[derive(Default)]
    pub struct MemwatchSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'a> SkelBuilder<'a> for MemwatchSkelBuilder {
        type Output = OpenMemwatchSkel<'a>;
        fn open(self) -> libbpf_rs::Result<OpenMemwatchSkel<'a>> {
            let opts = *self.obj_builder.opts();
            self.open_opts(opts)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
        ) -> libbpf_rs::Result<OpenMemwatchSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            #[allow(unused_mut)]
            let mut skel = OpenMemwatchSkel {
                obj,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    pub struct OpenMemwatchMapsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenMemwatchMapsMut<'_> {
        pub fn msg_ringbuf(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("msg_ringbuf").unwrap()
        }

        pub fn bss(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("memwatch.bss").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("memwatch.rodata").unwrap()
        }
    }

    pub struct OpenMemwatchMaps<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenMemwatchMaps<'_> {
        pub fn msg_ringbuf(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("msg_ringbuf").unwrap()
        }

        pub fn bss(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("memwatch.bss").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("memwatch.rodata").unwrap()
        }
    }

    pub struct OpenMemwatchProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenMemwatchProgs<'_> {
        pub fn perf_event_handler(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("perf_event_handler").unwrap()
        }
    }

    pub struct OpenMemwatchProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenMemwatchProgsMut<'_> {
        pub fn perf_event_handler(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("perf_event_handler").unwrap()
        }
    }

    pub mod memwatch_types {
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub MSG_ID: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}

        #[derive(Debug, Clone)]
        #[repr(C)]
        pub struct struct_ops {}

        impl struct_ops {}
    }

    pub struct OpenMemwatchSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        pub struct_ops: memwatch_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenSkel for OpenMemwatchSkel<'a> {
        type Output = MemwatchSkel<'a>;
        fn load(mut self) -> libbpf_rs::Result<MemwatchSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };

            Ok(MemwatchSkel {
                obj,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: MemwatchLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            &self.obj
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            &mut self.obj
        }
    }
    impl OpenMemwatchSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenMemwatchProgsMut<'_> {
            OpenMemwatchProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenMemwatchProgs<'_> {
            OpenMemwatchProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> OpenMemwatchMapsMut<'_> {
            OpenMemwatchMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> OpenMemwatchMaps<'_> {
            OpenMemwatchMaps { inner: &self.obj }
        }

        pub fn bss_raw(&self) -> *const memwatch_types::bss {
            self.skel_config
                .map_mmap_ptr(1)
                .unwrap()
                .cast::<memwatch_types::bss>()
        }

        pub fn bss(&self) -> &memwatch_types::bss {
            unsafe { &*self.bss_raw() }
        }

        pub fn bss_mut_raw(&mut self) -> *mut memwatch_types::bss {
            self.skel_config
                .map_mmap_ptr_mut(1)
                .unwrap()
                .cast::<memwatch_types::bss>()
        }

        pub fn bss_mut(&mut self) -> &mut memwatch_types::bss {
            unsafe { &mut *self.bss_mut_raw() }
        }
    }

    pub struct MemwatchMapsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl MemwatchMapsMut<'_> {
        pub fn msg_ringbuf(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("msg_ringbuf").unwrap()
        }

        pub fn bss(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("memwatch.bss").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("memwatch.rodata").unwrap()
        }
    }

    pub struct MemwatchMaps<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl MemwatchMaps<'_> {
        pub fn msg_ringbuf(&self) -> &libbpf_rs::Map {
            self.inner.map("msg_ringbuf").unwrap()
        }

        pub fn bss(&self) -> &libbpf_rs::Map {
            self.inner.map("memwatch.bss").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::Map {
            self.inner.map("memwatch.rodata").unwrap()
        }
    }

    pub struct MemwatchProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl MemwatchProgs<'_> {
        pub fn perf_event_handler(&self) -> &libbpf_rs::Program {
            self.inner.prog("perf_event_handler").unwrap()
        }
    }

    pub struct MemwatchProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl MemwatchProgsMut<'_> {
        pub fn perf_event_handler(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("perf_event_handler").unwrap()
        }
    }

    #[derive(Default)]
    pub struct MemwatchLinks {
        pub perf_event_handler: Option<libbpf_rs::Link>,
    }

    pub struct MemwatchSkel<'a> {
        pub obj: libbpf_rs::Object,
        struct_ops: memwatch_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
        pub links: MemwatchLinks,
    }

    unsafe impl Send for MemwatchSkel<'_> {}
    unsafe impl Sync for MemwatchSkel<'_> {}

    impl Skel for MemwatchSkel<'_> {
        fn object(&self) -> &libbpf_rs::Object {
            &self.obj
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            &mut self.obj
        }

        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = MemwatchLinks {
                perf_event_handler: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl MemwatchSkel<'_> {
        pub fn progs_mut(&mut self) -> MemwatchProgsMut<'_> {
            MemwatchProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> MemwatchProgs<'_> {
            MemwatchProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> MemwatchMapsMut<'_> {
            MemwatchMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> MemwatchMaps<'_> {
            MemwatchMaps { inner: &self.obj }
        }

        pub fn struct_ops_raw(&self) -> *const memwatch_types::struct_ops {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &memwatch_types::struct_ops {
            &self.struct_ops
        }

        pub fn bss_raw(&self) -> *const memwatch_types::bss {
            self.skel_config
                .map_mmap_ptr(1)
                .unwrap()
                .cast::<memwatch_types::bss>()
        }

        pub fn bss(&self) -> &memwatch_types::bss {
            unsafe { &*self.bss_raw() }
        }

        pub fn bss_mut_raw(&mut self) -> *mut memwatch_types::bss {
            self.skel_config
                .map_mmap_ptr_mut(1)
                .unwrap()
                .cast::<memwatch_types::bss>()
        }

        pub fn bss_mut(&mut self) -> &mut memwatch_types::bss {
            unsafe { &mut *self.bss_mut_raw() }
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        64, 0, 11, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 112, 101, 114, 102, 95, 101, 118, 101, 110, 116, 0, 46, 98, 115, 115, 0, 108, 105, 99,
        101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 46, 114, 111, 100, 97, 116, 97, 0, 109,
        101, 109, 119, 97, 116, 99, 104, 46, 98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95, 50, 0,
        103, 101, 116, 95, 109, 101, 115, 115, 97, 103, 101, 46, 95, 95, 95, 95, 102, 109, 116, 0,
        76, 66, 66, 48, 95, 51, 0, 112, 101, 114, 102, 95, 101, 118, 101, 110, 116, 95, 104, 97,
        110, 100, 108, 101, 114, 0, 77, 83, 71, 95, 73, 68, 0, 109, 115, 103, 95, 114, 105, 110,
        103, 98, 117, 102, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 112, 101, 114, 102,
        95, 101, 118, 101, 110, 116, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 0,
        0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70, 0, 0, 0, 0, 0, 3, 0, 136, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 1, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0,
        0, 0, 0, 0, 0, 0, 97, 0, 0, 0, 0, 0, 3, 0, 168, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0,
        18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 0, 0, 0, 0, 0, 0, 0, 123, 0, 0, 0, 17, 0, 4, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 142, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 0, 0, 0, 0, 24, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 121, 97, 0, 0, 0, 0, 0,
        0, 7, 1, 0, 0, 1, 0, 0, 0, 123, 22, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 8, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0,
        121, 99, 0, 0, 0, 0, 0, 0, 85, 0, 5, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 183, 2, 0, 0, 22, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 5, 0, 4, 0, 0, 0, 0, 0, 123,
        48, 0, 0, 0, 0, 0, 0, 191, 1, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0,
        132, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 114, 111, 112, 32, 109, 101, 115,
        115, 97, 103, 101, 32, 101, 110, 116, 114, 121, 32, 37, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 8, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 96, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 228, 2, 0, 0,
        228, 2, 0, 0, 42, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4,
        0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 27, 0, 0,
        0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0,
        42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 54,
        0, 0, 0, 21, 0, 0, 4, 168, 0, 0, 0, 62, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 66, 0, 0, 0, 11,
        0, 0, 0, 64, 0, 0, 0, 70, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0, 74, 0, 0, 0, 11, 0, 0, 0,
        192, 0, 0, 0, 78, 0, 0, 0, 11, 0, 0, 0, 0, 1, 0, 0, 81, 0, 0, 0, 11, 0, 0, 0, 64, 1, 0, 0,
        84, 0, 0, 0, 11, 0, 0, 0, 128, 1, 0, 0, 88, 0, 0, 0, 11, 0, 0, 0, 192, 1, 0, 0, 92, 0, 0,
        0, 11, 0, 0, 0, 0, 2, 0, 0, 95, 0, 0, 0, 11, 0, 0, 0, 64, 2, 0, 0, 98, 0, 0, 0, 11, 0, 0,
        0, 128, 2, 0, 0, 101, 0, 0, 0, 11, 0, 0, 0, 192, 2, 0, 0, 104, 0, 0, 0, 11, 0, 0, 0, 0, 3,
        0, 0, 107, 0, 0, 0, 11, 0, 0, 0, 64, 3, 0, 0, 110, 0, 0, 0, 11, 0, 0, 0, 128, 3, 0, 0, 113,
        0, 0, 0, 11, 0, 0, 0, 192, 3, 0, 0, 121, 0, 0, 0, 11, 0, 0, 0, 0, 4, 0, 0, 124, 0, 0, 0,
        11, 0, 0, 0, 64, 4, 0, 0, 127, 0, 0, 0, 11, 0, 0, 0, 128, 4, 0, 0, 133, 0, 0, 0, 11, 0, 0,
        0, 192, 4, 0, 0, 136, 0, 0, 0, 11, 0, 0, 0, 0, 5, 0, 0, 139, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0,
        0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 153, 0, 0, 0, 9, 0, 0, 0, 157, 0, 0,
        0, 1, 0, 0, 12, 12, 0, 0, 0, 176, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 180, 0, 0, 0, 0, 0, 0,
        8, 16, 0, 0, 0, 186, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 205, 0, 0, 0, 0, 0, 0,
        14, 14, 0, 0, 0, 1, 0, 0, 0, 212, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 18, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 217, 0, 0, 0, 0, 0, 0, 14, 19,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
        0, 21, 0, 0, 0, 4, 0, 0, 0, 22, 0, 0, 0, 225, 0, 0, 0, 0, 0, 0, 14, 22, 0, 0, 0, 0, 0, 0,
        0, 4, 2, 0, 0, 1, 0, 0, 15, 8, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 9, 2, 0, 0, 1,
        0, 0, 15, 4, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 17, 2, 0, 0, 1, 0, 0, 15, 16, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 23, 2, 0, 0, 1, 0, 0, 15, 22, 0, 0, 0, 23, 0, 0,
        0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73,
        90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110,
        116, 114, 105, 101, 115, 0, 109, 115, 103, 95, 114, 105, 110, 103, 98, 117, 102, 0, 112,
        116, 95, 114, 101, 103, 115, 0, 114, 49, 53, 0, 114, 49, 52, 0, 114, 49, 51, 0, 114, 49,
        50, 0, 98, 112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97,
        120, 0, 99, 120, 0, 100, 120, 0, 115, 105, 0, 100, 105, 0, 111, 114, 105, 103, 95, 97, 120,
        0, 105, 112, 0, 99, 115, 0, 102, 108, 97, 103, 115, 0, 115, 112, 0, 115, 115, 0, 117, 110,
        115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 0, 99, 116, 120, 0, 112, 101, 114,
        102, 95, 101, 118, 101, 110, 116, 95, 104, 97, 110, 100, 108, 101, 114, 0, 117, 54, 52, 0,
        95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32,
        108, 111, 110, 103, 0, 77, 83, 71, 95, 73, 68, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78,
        83, 69, 0, 103, 101, 116, 95, 109, 101, 115, 115, 97, 103, 101, 46, 95, 95, 95, 95, 102,
        109, 116, 0, 47, 104, 111, 109, 101, 47, 114, 111, 98, 101, 108, 105, 110, 47, 71, 105,
        116, 72, 117, 98, 47, 109, 101, 109, 119, 97, 116, 99, 104, 47, 98, 112, 102, 47, 109, 101,
        109, 119, 97, 116, 99, 104, 46, 98, 112, 102, 46, 99, 0, 32, 32, 32, 32, 77, 83, 71, 95,
        73, 68, 43, 43, 59, 0, 32, 32, 32, 32, 109, 115, 103, 95, 101, 110, 116, 95, 116, 32, 42,
        101, 110, 116, 32, 61, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 114,
        101, 115, 101, 114, 118, 101, 40, 38, 109, 115, 103, 95, 114, 105, 110, 103, 98, 117, 102,
        44, 32, 116, 111, 116, 97, 108, 95, 115, 105, 122, 101, 44, 32, 48, 41, 59, 0, 32, 32, 32,
        32, 105, 102, 32, 40, 33, 101, 110, 116, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 68, 114, 111, 112, 32, 109, 101,
        115, 115, 97, 103, 101, 32, 101, 110, 116, 114, 121, 32, 37, 100, 34, 44, 32, 77, 83, 71,
        95, 73, 68, 41, 59, 0, 32, 32, 32, 32, 101, 110, 116, 45, 62, 105, 100, 32, 61, 32, 77, 83,
        71, 95, 73, 68, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102,
        95, 115, 117, 98, 109, 105, 116, 40, 101, 110, 116, 44, 32, 48, 41, 59, 0, 32, 32, 32, 32,
        114, 101, 116, 117, 114, 110, 32, 48, 59, 0, 46, 98, 115, 115, 0, 108, 105, 99, 101, 110,
        115, 101, 0, 46, 109, 97, 112, 115, 0, 46, 114, 111, 100, 97, 116, 97, 0, 112, 101, 114,
        102, 95, 101, 118, 101, 110, 116, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0,
        0, 0, 20, 0, 0, 0, 140, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 31, 2, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 16, 0, 0, 0, 31, 2, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 245, 0, 0,
        0, 38, 1, 0, 0, 11, 104, 0, 0, 40, 0, 0, 0, 245, 0, 0, 0, 52, 1, 0, 0, 22, 112, 0, 0, 80,
        0, 0, 0, 245, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 245, 0, 0, 0, 123, 1, 0, 0, 9,
        116, 0, 0, 96, 0, 0, 0, 245, 0, 0, 0, 139, 1, 0, 0, 9, 120, 0, 0, 136, 0, 0, 0, 245, 0, 0,
        0, 192, 1, 0, 0, 13, 132, 0, 0, 144, 0, 0, 0, 245, 0, 0, 0, 214, 1, 0, 0, 5, 164, 0, 0,
        168, 0, 0, 0, 245, 0, 0, 0, 246, 1, 0, 0, 5, 204, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 179, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 0, 0, 0, 0, 0, 0, 0, 8,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0,
        0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 184, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 28, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        184, 2, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 184, 2, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 192, 2, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 2, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 9, 0,
        0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 2, 0, 0, 0, 0, 0, 0, 48, 0, 0,
        0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        165, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0,
        0, 0, 0, 38, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 170, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        64, 8, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
