name: cargo-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get-submodule
      run: git submodule update --init --recursive

    - name: Install-dependencies
      run: |
          sudo apt-get update
          sudo apt-get install clang llvm libelf1 libelf-dev zlib1g-dev

    - name: Install-bpftool
      run: |
          git clone https://github.com/libbpf/bpftool.git
          cd bpftool
          git submodule update --init
          cd src; make; sudo make install

    - name: Create-vmlinux-h
      run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h

    - name: Test
      run: |
        cargo clean
        cargo build --no-default-features
        cargo test --no-default-features --target-dir test_build
